import { build } from 'esbuild';
import { chmod, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { fileURLToPath } from 'node:url';

// This repository owns skill entrypoints, bundles, and tests.
// Renderer packages, their dependencies, and LICENSE stay in the upstream checkout.
const skillRoot = fileURLToPath(new URL('../../', import.meta.url));
const aliases = {
  '@glyphcss/charts': 'packages/charts/src/index.ts',
  '@glyphcss/diagrams/sequence': 'packages/diagrams/src/sequence/index.ts',
  '@glyphcss/diagrams/lanes': 'packages/diagrams/src/lanes/index.ts',
  '@glyphcss/diagrams': 'packages/diagrams/src/index.ts',
  glyphcss: 'packages/glyphcss/src/index.ts',
  '@glyphcss/core': 'packages/core/src/index.ts',
};

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: { source: { type: 'string' } },
});

if (!values.source) {
  process.stderr.write(
    'Missing upstream glyphcss checkout.\n'
    + 'Pass --source PATH to the repository that contains packages/charts, packages/diagrams, packages/glyphcss, packages/core, and LICENSE.\n'
    + 'From this nested checkout: node skills/runtime/build.mjs --source ..\n'
    + 'Or: npm run build -- --source ..\n',
  );
  process.exit(1);
}

const upstream = resolve(values.source);
for (const relative of ['LICENSE', ...Object.values(aliases)]) {
  try {
    await readFile(join(upstream, relative));
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
    process.stderr.write(`Upstream path ${upstream} is missing ${relative}.\nPass --source PATH to a glyphcss checkout, for example: node skills/runtime/build.mjs --source ..\n`);
    process.exit(1);
  }
}

function resolveInput(input) {
  return isAbsolute(input) ? input : resolve(skillRoot, input);
}

async function notices(metafile) {
  const packages = new Map();
  const used = new Set(Object.values(metafile.outputs).flatMap(output => Object.entries(output.inputs).filter(([, value]) => value.bytesInOutput > 0).map(([path]) => path)));
  for (const input of used) {
    if (!input.includes('node_modules/')) continue;
    let directory = dirname(resolveInput(input));
    while (directory !== dirname(directory)) {
      try {
        const manifest = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
        if (manifest.name) { packages.set(directory, manifest); break; }
      } catch (error) { if (error.code !== 'ENOENT') throw error; }
      directory = dirname(directory);
    }
  }
  const entries = [`glyphcss\n\n${await readFile(join(upstream, 'LICENSE'), 'utf8')}`];
  for (const [directory, manifest] of [...packages].sort(([, a], [, b]) => a.name.localeCompare(b.name))) {
    const files = (await readdir(directory)).filter(name => /^(LICENSE|LICENCE|COPYING)([.-]|$)/iu.test(name));
    if (!files.length) throw new Error(`No bundled license found for ${manifest.name}`);
    entries.push(`${manifest.name}@${manifest.version}\n\n${(await Promise.all(files.map(file => readFile(join(directory, file), 'utf8')))).join('\n')}`);
  }
  return entries.join('\n\n--------------------\n\n');
}

for (const name of ['charts', 'diagrams']) {
  const outdir = join(skillRoot, `skills/glyphcss-${name}/scripts`);
  await mkdir(outdir, { recursive: true });
  const outfile = join(outdir, 'render.mjs');
  const result = await build({
    absWorkingDir: skillRoot, entryPoints: [`skills/runtime/${name}.mjs`], outfile,
    alias: Object.fromEntries(Object.entries(aliases).map(([key, path]) => [key, join(upstream, path)])),
    bundle: true, platform: 'node', format: 'esm', target: 'node22',
    minify: true, legalComments: 'eof', metafile: true,
    banner: { js: '#!/usr/bin/env node\n// Generated by skills/runtime/build.mjs; bundled licenses: NOTICE.txt' },
  });
  await writeFile(join(outdir, 'NOTICE.txt'), await notices(result.metafile));
  await chmod(outfile, 0o755);
  process.stdout.write(`Built glyphcss-${name}: ${result.metafile.outputs[Object.keys(result.metafile.outputs)[0]].bytes} bytes\n`);
}
